osx_image: xcode7.3
language: objective-c
before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
install: bundle install --without=documentation --path ../travis_bundle_dir
script: bundle exec fastlane test
